<?php

namespace App\Enums;

enum AuditAction: string
{
    // Auth
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGOUT = 'LOGOUT';

        // Client & Sample
    case SAMPLE_REGISTERED = 'SAMPLE_REGISTERED';
    case SAMPLE_STATUS_CHANGED = 'SAMPLE_STATUS_CHANGED';

        // Sample Test
    case SAMPLE_TEST_CREATED = 'SAMPLE_TEST_CREATED';
    case SAMPLE_TEST_RESULT_SUBMITTED = 'SAMPLE_TEST_RESULT_SUBMITTED';
    case SAMPLE_TEST_OM_VERIFIED = 'SAMPLE_TEST_OM_VERIFIED';
    case SAMPLE_TEST_LH_VALIDATED = 'SAMPLE_TEST_LH_VALIDATED';

        // QC / Reagent
    case QC_EVALUATED = 'QC_EVALUATED';
    case REAGENT_CALC_APPROVED = 'REAGENT_CALC_APPROVED';
    case REAGENT_REQUEST_CREATED = 'REAGENT_REQUEST_CREATED';
    case REAGENT_REQUEST_UPDATED = 'REAGENT_REQUEST_UPDATED';
    case REAGENT_REQUEST_SUBMITTED = 'REAGENT_REQUEST_SUBMITTED';

        // Catalog (Consumables/Reagents)
    case CATALOG_ITEM_IMPORTED = 'CATALOG_ITEM_IMPORTED';
    case CATALOG_IMPORT_SUMMARY = 'CATALOG_IMPORT_SUMMARY';

        // Reporting
    case REPORT_GENERATED = 'REPORT_GENERATED';
    case REPORT_FINALIZED = 'REPORT_FINALIZED';

        // Delete
    case CLIENT_DELETED = 'CLIENT_DELETED';
    case SAMPLE_DELETED = 'SAMPLE_DELETED';
    case SAMPLE_TEST_DELETED = 'SAMPLE_TEST_DELETED';

        // Decisions
    case SAMPLE_TEST_DECISION_APPROVED = 'SAMPLE_TEST_DECISION_APPROVED';
    case SAMPLE_TEST_DECISION_REJECTED = 'SAMPLE_TEST_DECISION_REJECTED';

        // Intake
    case SAMPLE_INTAKE_CHECKLIST_SUBMITTED = 'SAMPLE_INTAKE_CHECKLIST_SUBMITTED';
    case SAMPLE_INTAKE_PASSED = 'SAMPLE_INTAKE_PASSED';
    case SAMPLE_INTAKE_FAILED = 'SAMPLE_INTAKE_FAILED';
    case SAMPLE_INTAKE_VALIDATED = 'SAMPLE_INTAKE_VALIDATED';
    case LAB_SAMPLE_CODE_ASSIGNED = 'LAB_SAMPLE_CODE_ASSIGNED';
    case WORKFLOW_GROUP_CHANGED = 'workflow_group_changed';
}
