<?php

namespace App\Enums;

enum AuditAction: string
{
    // Auth
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGOUT = 'LOGOUT';

        // Client & Sample
    case SAMPLE_REGISTERED = 'SAMPLE_REGISTERED';
    case SAMPLE_STATUS_CHANGED = 'SAMPLE_STATUS_CHANGED';

        // Sample Test
    case SAMPLE_TEST_CREATED = 'SAMPLE_TEST_CREATED';
    case SAMPLE_TEST_RESULT_SUBMITTED = 'SAMPLE_TEST_RESULT_SUBMITTED';
    case SAMPLE_TEST_OM_VERIFIED = 'SAMPLE_TEST_OM_VERIFIED';
    case SAMPLE_TEST_LH_VALIDATED = 'SAMPLE_TEST_LH_VALIDATED';

        // QC / Reagent
    case QC_EVALUATED = 'QC_EVALUATED';
    case REAGENT_CALC_APPROVED = 'REAGENT_CALC_APPROVED';

        // Reporting
    case REPORT_GENERATED = 'REPORT_GENERATED';
    case REPORT_FINALIZED = 'REPORT_FINALIZED';
}
